-- create table students (
--     id SERIAL PRIMARY KEY,
--     last_name VARCHAR(50),
--     first_name VARCHAR(50),
--     birth_date DATE
-- );
-- insert into students (first_name, last_name, birth_date)
-- values
--     ('Marc', 'Benichou', '02/11/1998'),
--     ('Yoan', 'Cohen', '03/12/2010'),
--     ('Lea', 'Benichou', '27/07/1987'),
--     ('Amelia', 'Dux', '  07/04/1996'),
--     ('David', 'Grez', '14/06/2003'),
--     ('Omer', 'Simpson', '03/10/1980');
--
-- select first_name, last_name, birth_date from students order by last_name

-- select first_name, last_name, birth_date from students order by birth_date DESC limit 1;
-- select first_name, last_name, birth_date from students limit 3 offset 2;